# Generated by Django 3.2.4 on 2021-08-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_auto_20210806_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('On the way', 'On the way'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
    ]
