# Generated by Django 3.2.6 on 2021-08-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0006_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On the way', 'On the way'), ('Packed', 'Packed'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('AA', 'Action_and_Adventure'), ('C', 'Classics'), ('CG', 'Comic_Book_or_Graphic_Novel'), ('DM', 'Detective_and_Mystery'), ('F', 'Fantasy'), ('HF', 'Historical Fiction'), ('H', 'Horror'), ('LF', 'Literary_Fiction')], max_length=2),
        ),
    ]
