# Generated by Django 3.2.6 on 2021-08-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0007_auto_20210806_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Packed', 'Packed'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('On the way', 'On the way')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('Action_and_Adventure', 'Action_and_Adventure'), ('Classics', 'Classics'), ('Comic_Book_or_Graphic_Novel', 'Comic_Book_or_Graphic_Novel'), ('Detective_and_Mystery', 'Detective_and_Mystery'), ('Fantasy', 'Fantasy'), ('Historical_Fiction', 'Historical_Fiction'), ('Horror', 'Horror'), ('Literary_Fiction', 'Literary_Fiction')], max_length=50),
        ),
    ]
