# Generated by Django 3.2.6 on 2021-08-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0010_auto_20210806_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('On the way', 'On the way'), ('Packed', 'Packed'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('AA', 'Action_and_Adventure'), ('C', 'Classics'), ('CG', 'Comic_Book_or_Graphic_Novel'), ('DM', 'Detective_and_Mystery'), ('F', 'Fantasy'), ('HF', 'Historical_Fiction'), ('H', 'Horror'), ('LF', 'Literary_Fiction')], max_length=2),
        ),
    ]
