# Generated by Django 3.2.4 on 2021-08-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0013_auto_20210807_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On the way', 'On the way'), ('Packed', 'Packed'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
    ]
